### ISSUE TITLE
Need to recompile error

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-viewer#1]
I'm trying to test the viewer, but I'm getting this error 

Module build failed (from /Users/rzu/Workspace/gaia-viewer/node_modules/ts-loader/index.js):
Error: Typescript emitted no output for /Users/abc/Workspace/gaia-viewer/node_modules/@gaia-project/engine/src/factions.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (/Users/abc/Workspace/gaia-viewer/node_modules/ts-loader/dist/index.js:39:15)
    at Object.loader (/Users/abc/Workspace/gaia-viewer/node_modules/ts-loader/dist/index.js:21:12)

@coyotte508 Can you help me on this?
Thanks
R

**Comment by rzulian** [comment]
solved linking local Gaia-engine.
thanks

**Comment by rzulian** [comment]
Looks promising, even if I didn’t fully understood the final architecture. Will you be able to run multiple games?
I tried a couple of months ago to create something using board game.io, but then I had to refocus on real work... anyway, I’m willing to help if you are committed to move it to the final stage
Best
R

**Comment by coyotte508** [comment]
Right now there's the engine and the viewer. The engine can be ported to anywhere as it's pure javascript (not the server part), for example it could be in an android app, a web page, or a server.

The plan in the future is to make a website using both the engine in backend, and the viewer as frontend. The website would have the seed & list of moves for each game in db, as well as player info. That's how multiple games are handled.

Of course the engine can be reused by other people for plenty of other things, like building an AI and so on.

Right now all that's available on the engine is board generation & faction choice. Like this:

```
init 5 seed
p1 faction terrans
p2 faction geodens
...
```

The next thing to do is to place buildings on the map, and do it with a click. We'll see how it goes.

**Comment by rzulian** [comment]
I can help on the build command on the engine side, if you need help. 
Where are you planning to store which building is in each space in the map?
Which is the best way to debug this architecture? Do you have suggestions or can you point me to tutorials?

**Comment by coyotte508** [comment]
I created a gitter room here: https://gitter.im/gaia-engine , so we can chat
