### ISSUE TITLE
Add tooltips on faction selection

### ISSUE THREAD

**Issue by coyotte508** [donkeytech/gaia-viewer#11]
For content, see page 20-21 of https://images-cdn.zmangames.com/us-east-1/filer_public/ce/89/ce890bfd-227e-4249-a52a-976bc5f20d19/en_gaia_rulebook_lo.pdf

**Comment by rzulian** [comment]
@coyotte508 : working on this. I've create a file with descriptions but I realised that's a lot of text that will be included in the code. Is this ok or is there another smart way?

**Comment by coyotte508** [comment]
It's basically like `data/reserach.ts`. Two pieces of data for each faction: planetary institute & ability. Might want to include html.
