### ISSUE TITLE
Improve Nevla's free actions

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-viewer#110]
When PI is enabled.
I find very counterintuitive  the current free actions. It would be better to have the real conversion (e.g 1PW -> 2C )

**Comment by coyotte508** [comment]
Well... We might have to fix engine too then? Or would it just be the buttons on the text?

**Comment by rzulian** [comment]
Yes, the engine too

**Comment by coyotte508** [comment]
Then it's probably just the engine that needs to be changed.

We need to remove all basic free actions when nevlas have their PI, and add those

- o,c for 2pw
- 2c for 1pw
- 2o for 3pw
- q for 2pw
- o for 2pw
- k for 2pw

I don't know how exactly it can be done, maybe the "plugin" system w/ adding an event / handler for free action generation for nevlas is enough.

We probably can remove the spending power too in player.data.

**Comment by rzulian** [comment]
I'll work on this
