### ISSUE TITLE
Final scoring points

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-viewer#32]
Current graphic can be challenging when scoring increases over 10 points. Instead of the grid display the value

**Comment by coyotte508** [comment]
Yes, currently if they go over 10 points they reset back to the beginning (like in TM when you have over 100 points you do a whole round).

It can be changed though, as long as it looks good! Maybe make the player tokens larger and put the number inside them.

Also, in games with 2 players, there should be the default points at 8 for the "third player".

**Comment by coyotte508** [comment]
I think that we can add a token when the player goes over 10: one token stays at 10, and the other starts at 1. 10 and 3 = 13, for example.
