### ISSUE TITLE
Create a custom federation is not possible

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-viewer#38]
In the test play wasn't possible to create a different custom federation and had to select the proposed.

**Comment by coyotte508** [comment]
I need a specifc example.

You can create a custom federation, if the alternate federation has different planets or the same number of satellites than the one suggested. The rules say you have to use the least number of satellites possible.

Give me the log & the federation you tried to build, and I'll check it out.

**Comment by rzulian** [comment]
It wan't possible in the UI to create a custom federation. You can use the test play. I wanted to form a federation but instead of the available, wanted to put a satellite in -1x1. Same number of satellites but different path
