### ISSUE TITLE
Allow to don't do a free action

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-viewer#40]
If you click to do a free action, and you change your mind, you are not able to return

**Comment by coyotte508** [comment]
Same as #39

**Comment by rzulian** [comment]
Well, is a little bit different. You click freeaction, and you change your mind, or you did it by mistake. You want to go back, but you didn't move.

**Comment by coyotte508** [comment]
You're right!

Anyway I did both (back & undoà
