### ISSUE TITLE
Use small square for ts

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-viewer#42]
It would make sense to use the small square for a ts, so you have visual glue for the upgrade to the PI, as the lab has a small circle and the ac has a big circle

**Comment by coyotte508** [comment]
I think it the bottom can be a square, with a triangle at the top.

something like `<polygon points='-0.3,-0.3 0,-0.45 0.3,-0.3 0.3,0.3 -0.3-0.3` />` in line height of https://github.com/donkeytech/gaia-viewer/blob/master/src/components/Building.vue
