### ISSUE TITLE
Highlight sectors when sectors are in final scoring

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-viewer#46]
When number of sector final score tile is in play, highlight the different sectors, so the player can understand where he is not present

**Comment by coyotte508** [comment]
Ok.

Hovering over an hex gives the sector of an hex, but yea, that's good too. Previous version (non-vue) had this!

**Comment by rzulian** [comment]
@coyotte508 Would you be able to work on this? It's definitely needed a lot of time

**Comment by coyotte508** [comment]
Reference of the commit pre-migration: https://github.com/donkeytech/gaia-viewer/commit/2cbdf38253998ea6e6df7e2e5329625bbd6a4c2a

**Comment by coyotte508** [comment]
Done: https://github.com/donkeytech/gaia-viewer/commit/9f491b1137e6608cb6dec64447ad6c15740f1452
