### ISSUE TITLE
Max resources in player info

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-viewer#47]
List max resources in player info.
12c/30, 6o/15.
Max resources should have a smaller font to do not decrease readability of the status

**Comment by coyotte508** [comment]
Or maybe just put the number of the resource in red? If it reaches 30c, 15k or 15o, the resource is in red.

**Comment by rzulian** [comment]
The purpose is to highlight that you are reaching the max with the current resources + incomes

**Comment by rzulian** [comment]
Related to #98
