### ISSUE TITLE
Map is not centered

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-viewer#67]

**Comment by coyotte508** [comment]
It is?

**Comment by rzulian** [comment]
I'm not seeing in the centre
![screen shot 2018-08-02 at 17 22 58](https://user-images.githubusercontent.com/29941924/43593776-eee28e6a-9678-11e8-93d7-fef090855753.png)

**Comment by coyotte508** [comment]
The [Map, Research board, Scoring board] group is centered

**Comment by rzulian** [comment]
Sorry, but visually it's not centred. There is a column underneath. And the same applies to the research.

**Comment by coyotte508** [comment]
Now the map is centered in the left column, and the research board in the right column
