### ISSUE TITLE
Scoring board should stay with Research board

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-viewer#74]
When going small it's requiring it's own space, messing the UI
<img width="932" alt="screen shot 2018-08-06 at 09 49 42" src="https://user-images.githubusercontent.com/29941924/43704761-02eb1a90-9961-11e8-8b40-106a46f8bb62.png">

**Comment by rzulian** [comment]
Probably linked to #35 , but the map shouldn't be on the same svg

**Comment by rzulian** [comment]
Is it online? 
This is what I'm getting on the iPhone X
![img_cfa81e2f15fb-1](https://user-images.githubusercontent.com/29941924/43711143-1900541a-9972-11e8-81b0-7959884a778f.jpeg)

**Comment by coyotte508** [comment]
It's not online, but you can check in the browser, in dev tools they allow you to switch to mobile mode: https://developers.google.com/web/tools/chrome-devtools/device-mode/

**Comment by coyotte508** [comment]
It's online, and I just tested.
