### ISSUE TITLE
Errata log

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-viewer#77]
This game https://gaiaform.io/game/brown-picture-6096
Has this initial log:
`init 2 brown-picture-6096
p1 faction geodens
geodens faction bescods
p2 faction ambas`
That is working on the server but not locally

**Comment by rzulian** [comment]
Problem is that in the server resources are totally wrong.
<img width="1276" alt="screen shot 2018-08-13 at 17 38 30" src="https://user-images.githubusercontent.com/29941924/44042140-d27f40c4-9f1f-11e8-8dcb-f3dfa1c2ea40.png">

**Comment by coyotte508** [comment]
This isn't really a gaia-viewer issue then.

Also, related to #72, it would help

**Comment by rzulian** [comment]
Where do we want to track those kind of errors? In engine?

**Comment by coyotte508** [comment]
Either that or site
