### ISSUE TITLE
Steps and colonized planet displayed wrongly

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-viewer#93]
Use Tokens instead?
![img_2774](https://user-images.githubusercontent.com/29941924/45746302-3a124600-bc03-11e8-9a31-42f30fa0aaa5.PNG)

**Comment by coyotte508** [comment]
Interesting. Try full refresh? Using tokens might work too...

**Comment by rzulian** [comment]
Full refresh usually works. I will take the update to token as my svg-vue exam ;)

**Comment by rzulian** [comment]
@coyotte508 what's the best approach: try to have it in the current component or create a new one?

**Comment by coyotte508** [comment]
I would add `<Token>` to the current component. But you might have trouble with line height, alignment and all that.

**Comment by rzulian** [comment]
Solved by 43aed36dac440620f0664c7a3f8ddd08bf5b501e
